[package]
name = "data-to-pics"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
colorous.workspace = true
data.workspace = true
image.workspace = true
indicatif.workspace = true
