[workspace]
members = [
    "compute/autovec",
    "compute/block",
    "compute/manualvec",
    "compute/naive",
    "compute/regular",
    "compute/shared",
    "data",
    "data-to-pics",
    "reaction"
]

[profile.release]
# Max performance at the cost of compile time
codegen-units = 1
# Good for perf profiling
debug = 1
