[workspace]
members = [
    "compute-bench",
    "compute-naive",
    "compute-regular",
    "data",
    "data-to-pics",
    "reaction"
]

[profile.release]
# Max performance at the cost of compile time
codegen-units = 1
# Good for perf profiling
debug = 1
