[package]
name = "naive"
version = "0.1.0"
edition = "2021"

[dependencies]
data = { path = "../../data" }
ndarray = "0.15"

[dev-dependencies]
bench = { path = "../bench" }
criterion = { version = "0.3", default-features = false }

[[bench]]
name = "benchmark"
harness = false