[package]
name = "reaction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# TODO: Use feature flags to plug into the various backends + pick backend
#       according to a preference order using cfg-if inside.

[features]
naive = ["compute-naive"]

[dependencies]
cfg-if = "1.0"
clap = { version = "4.1", features = ["derive"] }
data = { path = "../data" }
indicatif = "0.17"
compute-naive = { path = "../compute-naive", optional = true }

[dev-dependencies]
compute-naive = { path = "../compute-naive" }
