[package]
name = "block"
version = "0.1.0"
edition = "2021"

[dependencies]
autovec = { path = "../autovec" }
compute = { path = "../shared" }
data = { path = "../../data", features = ["slipstream"] }
hwloc2 = "2.2"
ndarray = "0.15"
once_cell = "1.17"

[dev-dependencies]
compute = { path = "../shared", features = ["criterion"] }
criterion = { version = "0.3", default-features = false }

[[bench]]
name = "benchmark"
harness = false