[package]
name = "compute"
version.workspace = true
edition.workspace = true

[features]
criterion = ["dep:criterion", "env_logger"]

[dependencies]
criterion = { workspace = true, optional = true }
env_logger = { workspace = true, optional = true }
data.workspace = true
ndarray.workspace = true
