[package]
name = "compute_gpu"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
vulkano.workspace = true
thiserror.workspace = true

[dev-dependencies]
# TODO: Remove once done testing
env_logger = "0.10"
