[package]
name = "compute_autovec"
version.workspace = true
edition.workspace = true

[dependencies]
cfg-if.workspace = true
compute.workspace = true
data = { workspace = true, features = ["slipstream"] }
slipstream.workspace = true

[dev-dependencies]
compute = { workspace = true, features = ["criterion"] }

[[bench]]
name = "benchmark"
harness = false