[package]
name = "autovec"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0"
data = { path = "../../data", features = ["slipstream"] }
ndarray = "0.15"
slipstream = "0.2"

[dev-dependencies]
bench = { path = "../bench" }
criterion = { version = "0.3", default-features = false }

[[bench]]
name = "benchmark"
harness = false